packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@google/genai"
  - "@prisma/client"
  - "@prisma/engines"
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs

overrides:
  ioredis: 5.11.1
